version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5187:8080"
      - "5187:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
