import Courses from "@eproject4/pages/user/Courses";

const seedData = () => {
  const courses= [
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 4000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Bussiness",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Bussiness",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Design",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Design",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Design",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 5000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Design",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 7000,
      price: 200,
    },

    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Design",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Design",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Bussiness",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Bussiness",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Design",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Design",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Design",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Design",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },

    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Design",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Design",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
  ];
  return courses.map((course, index) => ({
    id: index + 1,  
    ...course
  }));
};

export default seedData;
